name: Copper Skillet Courtyard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91956
title: Copper Skillet Courtyard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040402'
    - '#443a28'
    - '#aaa9a7'
    - '#ffdc1f'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
