name: Copper Skillet Courtyard
favicon: null
layout_spectrum: 0.34239870542660356
typography_spectrum: 0.7727697347290814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8506514630280435
  lightness: 0.08759168069809675
  saturation: 0.6861083458643407
  rhythmicContrast: 0.06012048479169607
purpose: []
