name: Copper Skillet Courtyard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91956
title: Copper Skillet Courtyard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#5c523f'
    - '#ddb76f'
    - '#a48873'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.06012048479169607
purpose: []
