name: Copper Skillet Courtyard
favicon: null
layout_spectrum: 0.93995
typography_spectrum: 0.94792
title: Copper Skillet Courtyard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211c20'
    - '#d6cdcb'
    - '#a0783e'
    - '#a72b16'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
